package com.test.pushnotification.exception;

public enum ErrorCode {
    GROUP_NOT_EXISTS, RUNTIME, NOT_GROUP_MEMBER, USER_NOT_EXISTS, ALREADY_SUBSCRIBED, ALREADY_UNSUBSCRIBED, USER_DOES_NOT_HAVE_PERMISSION
}
